### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ShamilBiktimirov** [Space-Systems/OPI#5]
Dear Davide,

I'm interested in working with you orbital propogator. My name is Shamil Biktimirov. I'm a PhD student at Skoltech in Moscow, Russia. 
I'm trying to install orbital propagator Thalassa on windows 10. The visual studio 2015 is installed as well as cmake and make. To start working with Thalassa I used attached instruction. 
1. When cmake is complited the following things was shown (please, see links)
https://i.imgur.com/uEBRQNL.png
https://i.imgur.com/ndZTVdn.png
2. The build folder looks like this
https://i.imgur.com/3nplAeC.png
3. But, there is no Makefile at the folder. Therefore, make is not built
https://i.imgur.com/1FhHDLY.png

Could you please help me to solve this issue?

Best regards,
Shamil

**Comment by mmoeckel** [comment]
Hi Shamil,
I can't see any issues in the screen shots - other than the CUDA and OpenCL SDKs not being found but it should build fine without it. Just to make sure, try and disable CUDA and OpenCL in the CMake configuration. In VS 2017 this is (awkwardly) done by right-clicking the CMakeLists.txt file, selecting "Change CMake Settings" and editing the JSON file. Just add the following to the build configuration you are using:
`"variables": [
  {
    "name": "ENABLE_CUDA_SUPPORT",
    "value": "OFF"
  },
  {
    "name": "ENABLE_CL_SUPPORT",
    "value": "OFF"
  }
]`

I'm a little confused - you said you are trying to install Thalassa (I'm assuming you're talking about [this project](https://gitlab.com/souvlaki/thalassa)) but the screen shots show the OPI build process. I'm not familiar with Thalassa, does it use OPI? What is the connection?
Cheers,
  Marek

**Comment by ShamilBiktimirov** [comment]
Hi @mmoeckel,

Yes, I'm talking about [this project](https://gitlab.com/souvlaki/thalassa/boards). Nevertheless, to work with the project, I use the code from the GitHub. OPI is an Orbital Propagator Interface; this is what I've meant. In your answer, you are talking about problems with Cmake. However, the problems are with running Makefile. Cmake configurates and generates Makefile https://i.imgur.com/KaOS7eC.png , but I can not run it in VS 2017. Here is my built folder - https://i.imgur.com/0DclHre.png. If I try to run it, the following things happen https://i.imgur.com/ze378Y3.png.
If I use the terminal to run makefile as it is mentioned in the build instruction, it says that there is no such file to tun.
Do you have any suggestions what can I do?

Best,
Shamil

**Comment by mmoeckel** [comment]
Hi Shamil,
the build folder looks okay to me. Can you try building just the OPI library first and see what happens? (From a clean build tree, right-click "OPI" in the Solution Explorer and select "build"). If that works, try building everything else afterwards. The CMake scripts auto-generate a few source files and Visual Studio might not pick up on the correct build order.
Please let me know if this solves your issue.
Cheers,
  Marek

**Comment by mmoeckel** [comment]
Marking this as closed since I haven't heard back from you and it looks like the issue is not a bug in the OPI code. Please reopen if further action is required.
